### ISSUE TITLE
Modal Windows Escape and Erase on return/enter click 

### ISSUE THREAD

**Issue by patrickwroach** [patrickwroach/inc#1]
Enter should close and submit the input, but doesn't at this point.  For some reason it closes the window and erases entered content.  
We should be able to simply bind an enter click to the submit button, when the window is active.

**Comment by JHandzel** [comment]
All modals now submit when enter's pressed as long as one of the inputs have focus.

Changed logic for how modals get rendered slightly.

To do: Modals should be put in their own components and share them if possible (Edit Name Modal for InitGroup and Character, for example)
